assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{commitId}"

platform: Any CPU

configuration: Release
